<a href="https://colab.research.google.com/github/usmarcv/oficina-ia/blob/main/Oficina_IA_Part_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Manipulação de variáveis e constantes

## Variáveis e constantes

- Por meio de variáveis que um algortimo “guarda” os dados do problema
- Todo dado que tem a possibilidade de ser alterado no decorrer do tempo deverá ser tratado como uma variável
- Quando um dado não tem nenhuma possibilidade de variar no decorrer do tempo, deverá ser tratado como constante

Exemplo: calcular a área de um triângulo. Sabemos que a fórmula para o cálculo da área de um triângulo é BASE * ALTURA / 2. **Base** e **altura** são dados que irão variar no decorrer do “tempo de execução”. O número 2 da fórmula é um dado constante, pois sempre terá o mesmo valor

## Tipo de variáveis

- Inteiros: valores positivos ou negativos, que não possuem uma parte fracionária. Exemplos: 1, 30, 40, 12, -50
- Float (real): valores positivos ou negativos, que podem possuir uma parte fracionária (também podem ser inteiros). Exemplos: 1.4, 6.7, 10.3, 100, -47
- Caracteres (char ou string): qualquer elemento presente no teclado. Exemplos: “Maria”, “João”, ‘M’, ‘F’
- Lógico (boleano): verdadeiro ou falso. Exemplos: true, false, 1, 0


## Nomes de variáves

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:
### Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

## Variáveis inteiras

In [ ]:
numero = -3
numero_jogos = 14
numero_convidados = 15

In [ ]:
numero

-3

In [ ]:
print(numero)

-3


In [ ]:
print(numero, numero_convidados)

-3 15


## Variáveis float (ponto flutuante)

> Indented block



In [ ]:
pi = 3.14
numero_euler = 2.71
escala_terremoto = -4.55

In [ ]:
print(pi)
print(numero_euler)
print(escala_terremoto)

3.14
2.71
-4.55


## Strings e chars

In [ ]:
letra = 'a'
palavra1 = 'linguagem de programação'
palavra2 = 'Python'

In [ ]:
print(letra, palavra1)

a linguagem de programação


In [ ]:
print('Estou aprendendo uma', palavra1)

Estou aprendendo uma linguagem de programação


In [ ]:
print('Esta', palavra1, 'se chama', palavra2)

Esta linguagem de programação se chama Python


In [ ]:
idade = int(input('Digite sua idade:'))
print('Sua idade é ', idade)

Digite sua idade:30
Sua idade é  30


In [ ]:
pH = float(input('Qual o pH do solo durante a última medição?'))
print('O pH medido foi ', pH)

Qual o pH do solo durante a última medição?12
O pH medido foi  12.0


In [ ]:
nome = str(input('Qual o seu nome?'))
print('Seu nome é', nome)

Qual o seu nome?Márcus
Seu nome é Márcus


In [ ]:
idade

30

## Um pouco de operações matemáticas

## Operações matemáticas

In [ ]:
a = 5
b = 3
print(a, b)

5 3


In [ ]:
a + b

8

In [ ]:
print('A soma é', a + b)

A soma é 8


In [ ]:
print('A subtração é', a - b)

A subtração é 2


In [ ]:
print('A divisão é', a / b)

A divisão é 1.6666666666666667


In [ ]:
print('A multiplicação é', a * b)

A multiplicação é 15


In [ ]:
print('O resto da divisão é', 10 % 3)

O resto da divisão é 1


In [ ]:
5 * 5 * 5 * 5

625

In [ ]:
print('5 elevado a 4 é', 5**4)

5 elevado a 4 é 625


In [ ]:
import math
math.sqrt(81)

9.0

## Arredondamento

In [ ]:
casos_doenca = 134
numero_habitantes = 34432
casos_por_habitante = casos_doenca / numero_habitantes
print(casos_por_habitante)

0.003891728624535316


In [ ]:
round(casos_por_habitante, 6)

0.003892

In [ ]:
print('O número de casos por habitante é de', round(casos_por_habitante, 4))

O número de casos por habitante é de 0.0039


# 2. Operadores lógicos e relacionais




## Operadores lógicos

In [ ]:
a = True
b = False

In [ ]:
print(a, b)

True False


In [ ]:
a and b

False

In [ ]:
a & b

False

In [ ]:
c = a and b
print("'A' e 'B' são iguais é", c)

'A' e 'B' são iguais é False


In [ ]:
a or b

True

In [ ]:
a | b

True

In [ ]:
d = a or b
print("'A' ou 'B' é igual a", d)

'A' ou 'B' é igual a True


In [ ]:
not a

False

In [ ]:
not b

True

## Operadores relacionais

In [ ]:
5 > 3

True

In [ ]:
5 < 3

False

In [ ]:
5 >= 5

True

In [ ]:
5 <= 3

False

In [ ]:
5 == 3

False

In [ ]:
5 != 3

True

# 3. Operadores condicionais

In [ ]:
if 5 > 3:
  print('5 é maior que 3')

5 é maior que 3


In [ ]:
if 5 > 6:
  print('5 é maior')
else:
  print('5 não é maior')

5 não é maior


In [ ]:
if 5 > 5:
    print('5 é maior')
elif 5 < 5:
    print('5 é menor')
else:
    print('São iguais')

São iguais


In [ ]:
n = 3
if n == 4:
  print('n é igual a 4')
else:
  if n == 3:
    print('n igual a 3')
  else:
    print('n não é igual a 4 nem 3')

n igual a 3


In [ ]:
x = 2
y = 3

if (x > 1) and (y % 2 == 0):
  print('x é maior que 1 e 2 é par')
else:
  print('Uma ou nenhuma das condições acima foram satisfeitas')

Uma ou nenhuma das condições acima foram satisfeitas


# 4. Estruturas de repetição - for

In [ ]:
print(1)
print(2)
print(3)
print(4)
print(5)

1
2
3
4
5


In [ ]:
for numero in range(1, 6):
  print(numero)

1
2
3
4
5


In [ ]:
for numero in range(5, 0, -1):
  print(numero)

5
4
3
2
1


In [ ]:
5 + 4 + 3 + 2 + 1

15

In [ ]:
soma = 0
for numero in range(1, 6):
  soma = soma + numero
  #print(soma)

print(soma)

15


In [ ]:
palavra = 'sorvete'
for letra in palavra:
  #print(letra)
  if letra == 'v':
    print('Achou a letra v')

Achou a letra v


In [ ]:
for i in range(0,5):
  print(i)
  print('---')
  for j in range(0,3):
    print(j)
  print()

0
---
0
1
2

1
---
0
1
2

2
---
0
1
2

3
---
0
1
2

4
---
0
1
2



#5. Estruturas de repetição - while

In [ ]:
numero = 1
while numero < 6:
  print(numero)
  numero += 1
print('---')

1
2
3
4
5
---


In [ ]:
numero = 5
while numero > 0:
  print(numero)
  numero -= 1

5
4
3
2
1


In [ ]:
1 + 2 + 3 + 4 + 5

15

In [ ]:
soma = 0
numero = 1
while numero < 6:
  soma += numero
  numero += 1
print(soma)

15


In [ ]:
numero = 12
while numero < 1 or numero > 10:
  numero = int(input('Digite um número de 1 a 10: '))

Digite um número de 1 a 10: 5


# 6. Funções

- Trechos de programa que recebem um determinado nome e podem ser chamados várias vezes durante a execução 
- Principais vantagens: reutilização de código, modularidade e facilidade de manutenção do sistema

## Função sem parâmetro e sem retorno



In [ ]:
def mensagem():
  print('Texto da função')

In [ ]:
mensagem()
mensagem()
mensagem()

Texto da função
Texto da função
Texto da função


## Função com passagem de parâmetro

In [ ]:
def mensagem(texto):
  print(texto)

In [ ]:
mensagem('texto 1')
mensagem('texto 2')
mensagem('texto 3')

texto 1
texto 2
texto 3


In [ ]:
def soma(a, b):
  print(a + b)

In [ ]:
soma(2, 3)

5


In [ ]:
soma(3, 3)
soma(1, 2)

6
3


## Função com passagem de parâmetros e retorno

In [ ]:
def soma(a, b):
  return a + b

In [ ]:
soma(3, 2)

5

In [ ]:
# r = 7
r = soma(3, 2)
print(r)

5


In [ ]:
def calcula_energia_potencial_gravitacional(m, h, g = 10):
  '''
  Calcula a energia potencial gravitacional
  Argumentos:
  m: massa, entrada como uma variável float
  h: altura, entrada como uma variável float

  Argumento opcional:
  g: aceleração gravitacional, com valor default de 10
  '''
  e = g * m * h
  return e

In [ ]:
calcula_energia_potencial_gravitacional(30, 12)

3600

In [ ]:
calcula_energia_potencial_gravitacional(30, 12, 9.8)

3528.0

In [ ]:
help(calcula_energia_potencial_gravitacional)

Help on function calcula_energia_potencial_gravitacional in module __main__:

calcula_energia_potencial_gravitacional(m, h, g=10)
    Calcula a energia potencial gravitacional
    Argumentos:
    m: massa, entrada como uma variável float
    h: altura, entrada como uma variável float
    
    Argumento opcional:
    g: aceleração gravitacional, com valor default de 10



# 7. Coleções

## Tuplas

In [ ]:
tupla = ('Homo sapiens', 'Canis familiaris', 'Felis catus')

In [ ]:
tupla

('Homo sapiens', 'Canis familiaris', 'Felis catus')

In [ ]:
tupla[0]

'Homo sapiens'

In [ ]:
tupla.index('Canis familiaris')

1

In [ ]:
for elemento in tupla:
  print(elemento)

Homo sapiens
Canis familiaris
Felis catus


## Listas

In [ ]:
l1 = ['Homo sapiens', 'Canis familiaris', 'Felis catus']
l2 = ['Xenopus laevis', 'Ailuropoda melanoleuca']

In [ ]:
l3 = l1 + l2
print(l3)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Xenopus laevis', 'Ailuropoda melanoleuca']


In [ ]:
l2

['Xenopus laevis', 'Ailuropoda melanoleuca']

In [ ]:
l2_2 = l2 * 2
print(l2_2)

['Xenopus laevis', 'Ailuropoda melanoleuca', 'Xenopus laevis', 'Ailuropoda melanoleuca']


In [ ]:
l1[0]

'Homo sapiens'

In [ ]:
l1

['Homo sapiens', 'Canis familiaris', 'Felis catus']

In [ ]:
l1[0:2]

['Homo sapiens', 'Canis familiaris']

In [ ]:
l1.append('Gorila gorila')
print(l1)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Gorila gorila']


In [ ]:
l1.remove('Felis catus')
print(l1)

['Homo sapiens', 'Canis familiaris', 'Gorila gorila']


In [ ]:
del(l1)

In [ ]:
print(l1)

NameError: ignored

In [ ]:
for item in l2_2:
  print(item)

Xenopus laevis
Ailuropoda melanoleuca
Xenopus laevis
Ailuropoda melanoleuca


## Dicionários

In [ ]:
coleta = {'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14}

In [ ]:
coleta['Aedes aegypt']

32

In [ ]:
coleta['Rhodnius montenegrensis'] = 11

In [ ]:
print(coleta)

{'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14, 'Rhodnius montenegrensis': 11}


In [ ]:
del(coleta)['Aedes albopictus']
print(coleta)

{'Aedes aegypt': 32, 'Anopheles darlingi': 14, 'Rhodnius montenegrensis': 11}


In [ ]:
coleta.items()

dict_items([('Aedes aegypt', 32), ('Anopheles darlingi', 14), ('Rhodnius montenegrensis', 11)])

In [ ]:
coleta.keys()

dict_keys(['Aedes aegypt', 'Anopheles darlingi', 'Rhodnius montenegrensis'])

In [ ]:
coleta.values()

dict_values([32, 14, 11])

In [ ]:
coleta2 = {'Anopheles gambiae': 13, 'Anopheles deaneorum': 14}
print(coleta2)

{'Anopheles gambiae': 13, 'Anopheles deaneorum': 14}


In [ ]:
coleta.update(coleta2)
print(coleta)

{'Aedes aegypt': 32, 'Anopheles darlingi': 14, 'Rhodnius montenegrensis': 11, 'Anopheles gambiae': 13, 'Anopheles deaneorum': 14}


In [ ]:
coleta.items()

dict_items([('Aedes aegypt', 32), ('Anopheles darlingi', 14), ('Rhodnius montenegrensis', 11), ('Anopheles gambiae', 13), ('Anopheles deaneorum', 14)])

In [ ]:
for especie, num_especimes in coleta.items():
  print(f'Espécie: {especie}, número de espécimes coletados: {num_especimes}')

Espécie: Aedes aegypt, número de espécimes coletados: 32
Espécie: Anopheles darlingi, número de espécimes coletados: 14
Espécie: Rhodnius montenegrensis, número de espécimes coletados: 11
Espécie: Anopheles gambiae, número de espécimes coletados: 13
Espécie: Anopheles deaneorum, número de espécimes coletados: 14


## Conjuntos (set)

In [ ]:
biomeleculas = ('proteína', 'ácidos nucleicos', 'carboidrato', 'lipídeo',
                'ácidos nucleicos', 'carboidrato', 'carboidrato', 'carboidrato')

In [ ]:
print(biomeleculas)

('proteína', 'ácidos nucleicos', 'carboidrato', 'lipídeo', 'ácidos nucleicos', 'carboidrato', 'carboidrato', 'carboidrato')


In [ ]:
print(set(biomeleculas))

{'ácidos nucleicos', 'carboidrato', 'lipídeo', 'proteína'}


In [ ]:
c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7}
c3 = c1.intersection(c2)

In [ ]:
print(c3)

{3, 4, 5}


In [ ]:
c1.difference(c2)

{1, 2}

In [ ]:
c2.difference(c1)

{6, 7}

# 8. Introdução ao Numpy



Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [ ]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Criando arrays Numpy

In [ ]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [ ]:
km = np.array([1000, 2300, 4987, 1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [ ]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [ ]:
km = np.loadtxt(fname = "carros-km.txt", dtype = int)
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
Acessorios = np.array(dados)

In [ ]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [ ]:
km.shape

(258,)

In [ ]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [ ]:
np_array = np.arange(1000000)

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 74.6 ms, sys: 0 ns, total: 74.6 ms
Wall time: 76.4 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 7.58 s, sys: 1.73 s, total: 9.3 s
Wall time: 9.3 s


## Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
# idade = 2019 - anos

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2019 - anos

In [ ]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [ ]:
km_media = km/ idade
km_media

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

### Operações com arrays de duas dimensões

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
km_media = dados[0]/ (2019 - dados[1])
km_media

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

## Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
item = 6
index = item - 1
contador[index]

5

In [ ]:
contador[-1]

9

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [ ]:
dados[1][2]

1990.0

In [ ]:
dados[1, 2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[1:4]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [ ]:
dados[:, 1:4][0]

array([ 5712., 37123.,     0.])

In [ ]:
dados[:, 1:3][0]/ (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

# Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [ ]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [ ]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [ ]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [ ]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [ ]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5, 2), order = 'C') # indexação da linguagem C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5, 2), order = 'F') # indexação da linguagem Fortran

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(info_carros).reshape((2, 5)).T

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [ ]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados_new.resize((3, 5), refcheck=False)

In [ ]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [ ]:
dados_new[2] = dados_new[0]/ (2019 - dados_new[1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

## Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset)

48489.14648578811

In [ ]:
np.mean(dataset, axis=0) # média por coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis=1) # média por linha

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18400.79333333, 56984.80666667, 59177.8       ,
       36526.53      , 30190.46333333, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.46666667, 77867.61333333, 76878.21666667,
       41205.07      , 24462.03333333, 34386.25      , 35817.28      ,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.19666667, 41766.95666667, 25768.39333333, 34876.18      ,
       54475.06333333, 59333.43      , 29553.44666667, 75040.79666667,
       39881.91      , 22655.23333333, 52057.21666667, 31725.88333333,
       22240.03333333, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [ ]:
np.mean(dataset[:, 1])

44499.41472868217

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [ ]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
dataset[:, 1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[:, 1], axis=0)

11480849.0